### PR TITLE
Update gradle scripts + change deprecated ActionBarActivity to AppCompatActivity 

### PR DESCRIPTION
**Pull request by CyberNyanta**

### CODE REVIEW

**Comment by CyberNyanta** [comment]
You need to update sdk on your build machine

**Comment by xiprox** [comment]
Hello!

Thank you very much for contributing.

As a principle, I try not to merge PRs that fail though. Could you please update the required SDK and tool versions in the [Travis configuration file](https://github.com/xiprox/WaniKani-for-Android/blob/master/.travis.yml)? If you have any difficulties, I would gladly try to help.

Once we get an OK from Travis, I will be happy to merge this PR.

**Comment by CyberNyanta** [comment]
Updated

**Comment by xiprox** [comment]
Thank you once again.

**Pull request merged**
