### PR TITLE
Some bugfixes and performance improvements

### LINKED ISSUE #10: Critical items all appear as locked
All my critical items appear as locked from the main dashboard,  and greyed out.  Clicking on them says progress is locked,  but I definitely seen them in reviews.

### PR DESCRIPTION
**Pull request by Gustorn**
This should fix the bugs in the Critical Items and Recently Unlocked views. It also speeds up the Progress Details screen by caching fonts (it previously froze my phone for a few seconds, now it works as expected). 

Closes #10

### CODE REVIEW

**Comment by xiprox** [comment]
Thanks for the contribution! Must have been painful...fixing that code. :stuck_out_tongue:

**Comment by xiprox** [comment]
Note: ItemDetailsActivity is messed up at this point. Not sure if anything here did it. Won't be looking into it much though as I'll be working on a redesign there.

**Comment by Gustorn** [comment]
The ItemDetailsActivity seems to work for me, what's the issue you're having?

**Comment by xiprox** [comment]
Try a Kanji item that is burned. Some fields (User synonyms, reading/meaning notes) that should be `GONE` are there.

**Comment by Gustorn** [comment]
That would explain it, I only have stuff that's enlightened at everything seemed fine there. One things that is messed up is Radicals/Kanji/Vocab lists, I think I missed some enum<->string comparisons. I'll send an other PR to fix it.

**Comment by xiprox** [comment]
No issues. :+1:

**Comment by Gustorn** [comment]
Oh, never mind, the indicator on those lists is the SRS level. It's confusing since it uses the same colors for Radical/Kanji/Vocab as Enlightened/Apprentice/Guru. I've been thinking about doing some performance improvements and fixing #5, but if you're doing a redesign then I'm probably not going to do it (it's a fairly time-consuming task).

**Comment by xiprox** [comment]
Well, I'm only using what the site uses itself, so yeah...

I'm doing the redesign only on the ItemDetailsActivity. Not much else. Feel free to work on that.

**Comment by xiprox** [comment]
Redesign done in ddd2939.

**Pull request merged**
