### PR TITLE
Usability improvements (lesson quit warn dialog, keep screen awake, default single mode, etc)

### PR DESCRIPTION
**Pull request by Aralox**
Hi İhsan, 
I've incorporated a few usability changes which makes the app a little more pleasant/efficient for me, and thought I'd share them. This is my first time forking and creating a pull request, so apologies if I screwed something up. 

Here is a copy of my commit message:
- Default 'single' mode selected.
- Keep screen on during lessons and reviews.
- Confirmation dialog if back button pressed during lessons.
- Added ".?!" to banned characters in meaning textbox.
- Rearranged dashboard, moved progress card up (so overall lesson progress can be seen without scrolling).
- Updated build.gradle SDK version and tools from 23 to 24
- Changed gradle version from 2.2.0-alpha2 to 2.0.0, because builds with the alpha version crashed for me.

An issue I would also really like to fix but cannot figure out how:
- When I click on the 'notes' box in lessons/reviews, the internal browser resizes after the keyboard appears, causing the keyboard to disappear again. This makes it impossible to edit notes.

Please let me know if you have any ideas on how to approach that problem.

I know the situation is pretty bad over in Turkey right now (I'm in Australia), so don't stress about replying to this any time soon. I hope you and your family are alright. 

Love, 
Aralox

### CODE REVIEW

**Comment by xiprox** [comment]
Hello Aralox,


Most of the changes you made are things I had thought would be cool to work on. I'll be further reviewing them when I'm able to.

**Comment by xiprox** [comment]
Thank you for the contribution once again!

You forgot to mention "backspace triggers ignore" though. That's a nice addition!

**Comment by Aralox** [comment]
You're welcome! :)

There's only a couple more things that I really want to do before I'd be fully satisfied with the app, but am too busy with university at the moment. Two bugs I want to fix, really:
- Crashing when loading review info in the home screen (I'd approach this by selectively disabling fragments to isolate the problem, but you might be able to pinpoint the source of the crashes much more easily)
- The duplicate app bar. I asked a [question about this on SO](http://stackoverflow.com/questions/38802110/hide-app-action-bar-when-copy-pasting-contextual-action-bar) a while ago, but got the 'Tumbleweed' badge for it! XD

**Comment by Aralox** [comment]
For me,  it crashes sometimes after reviews and sometimes when first opening the app. I only use a horizontal orientation, but maybe it's crashing for the same reason. 
Thanks for having a look at the toolbar stuff, I'll definitely try your suggestion when I get back into this. I will be able  to probably sometime in Decembe. (I'llalso try  toput  in theauto advance  feature around the) 
 sorry if this  message gets mangled,  it  came out pretty strange on my phone

**Comment by xiprox** [comment]
What does logcat say? 

I see. I'll hopefully be able to do some touches by that time too.

And no issues. I got you.

**Comment by xiprox** [comment]
Hello, @Aralox. Just letting you know that I squashed double app bar stuff in 79fb614.

**Comment by Aralox** [comment]
Hey İhsan, Thank you for fixing this and letting me know! 
I haven't gotten back into this for a number of reasons, but am in the process of getting a new phone so I plan on picking this up again soon. 
Thanks also for the heads up about the SO answer. :)

**Pull request merged**
